import $ from 'jquery';
import 'jquery-powertip';
import 'slick-carousel/slick/slick';
import 'mmenu-light';
import '@fortawesome/fontawesome-free/js/all';
import '@fortawesome/fontawesome-free/js/brands';
import './magic';
import './homepage';
import './burger';
import './learn';
